# Generated by Django 4.2.5 on 2023-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-data"]},
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
