# Generated by Django 4.2.5 on 2023-10-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="poster",
            field=models.ImageField(null=True, upload_to="posters/"),
        ),
    ]
