# Generated by Django 4.2.5 on 2023-10-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.DateTimeField(null=True, verbose_name="Дата проведения"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание мероприятия"),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_done",
            field=models.BooleanField(
                default=False, verbose_name="Прошедшее мероприятие"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizers",
            field=models.TextField(blank=True, verbose_name="Организаторы"),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Место проведения"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="poster",
            field=models.ImageField(
                null=True, upload_to="posters/", verbose_name="Афиша"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                max_length=255, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название мероприятия"),
        ),
    ]
