# Generated by Django 4.2.5 on 2023-11-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_docs_event_main_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата проведения"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="docs",
            field=models.URLField(
                blank=True,
                null=True,
                verbose_name="Ссылка на диск с файлами мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizers",
            field=models.TextField(verbose_name="Организаторы"),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место проведения"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="posters/", verbose_name="Афиша"
            ),
        ),
    ]
