# Generated by Django 4.2.5 on 2023-11-21 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0007_remove_event_main_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="main_organizer",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель",
            ),
        ),
    ]
